# Generated by Django 3.0.8 on 2020-10-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilit', '0005_delete_explorationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=150, null=True)),
                ('min_length', models.IntegerField(null=True)),
                ('max_length', models.IntegerField(null=True)),
                ('min_value', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('max_value', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('completeness', models.DecimalField(decimal_places=6, max_digits=20)),
                ('non_null_count', models.IntegerField(null=True)),
                ('uniqueness', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('unique_value_count', models.IntegerField(null=True)),
                ('common_values', models.CharField(max_length=500, null=True)),
                ('numeric_percentage', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('date_percentage', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('file_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilit.ExplorationFiles')),
            ],
            options={
                'verbose_name_plural': 'Exploration data in raw form',
            },
        ),
    ]
