# Generated by Django 3.0.8 on 2020-10-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20201027_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesbasedprofilingdata',
            name='error_counts',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='RuleTemplateErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100)),
                ('error_message', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
