# Generated by Django 3.0.8 on 2020-11-04 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201028_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesbasedprofilingdata',
            name='completenesss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rulesbasedprofilingdata',
            name='confomrity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rulesbasedprofilingdata',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rulesbasedprofilingdata',
            name='uniqueness',
            field=models.IntegerField(null=True),
        ),
    ]
