# Generated by Django 3.0.8 on 2020-11-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201104_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesbasedprofilingdata',
            old_name='attribute',
            new_name='attribute_failed',
        ),
    ]
