# Generated by Django 3.0.8 on 2020-11-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201105_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesbasedprofilingdata',
            old_name='completenesss',
            new_name='completeness',
        ),
        migrations.RenameField(
            model_name='rulesbasedprofilingdata',
            old_name='confomrity',
            new_name='conformity',
        ),
    ]
