# Generated by Django 3.0.8 on 2020-11-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201105_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesbasedprofilingdata',
            old_name='error_counts',
            new_name='total_errors',
        ),
    ]
