# Generated by Django 3.0.8 on 2020-11-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201112_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesbasedprofilingdata',
            old_name='total_errors',
            new_name='total',
        ),
    ]
