# Generated by Django 3.0.8 on 2020-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20201112_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='completeness',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='conformity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='uniqueness',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
