# Generated by Django 3.0.8 on 2020-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20201112_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='completeness',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='conformity',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rulesbasedprofilingdata',
            name='uniqueness',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
