# Generated by Django 3.0.8 on 2020-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201112_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesbasedprofilingdata',
            name='total_errors',
            field=models.IntegerField(null=True),
        ),
    ]
