# Generated by Django 3.1.3 on 2020-11-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20201116_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_a_total', models.IntegerField(null=True)),
                ('data_file_b_total', models.IntegerField(null=True)),
                ('match_file_count', models.IntegerField(null=True)),
                ('unmatched_file_count', models.IntegerField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
