# Generated by Django 3.1.3 on 2020-12-01 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_matchingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingdata',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
