# Generated by Django 3.1.3 on 2020-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_matchingdata_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingdata',
            old_name='match_file_count',
            new_name='match_count',
        ),
        migrations.RemoveField(
            model_name='matchingdata',
            name='unmatched_file_count',
        ),
        migrations.AddField(
            model_name='matchingdata',
            name='data_count',
            field=models.IntegerField(null=True),
        ),
    ]
