# Generated by Django 3.1.3 on 2020-12-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201202_1118'),
        ('dashboard', '0017_auto_20201125_1435'),
    ]

    operations = [
    ]
