# Generated by Django 3.1.3 on 2020-12-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20201209_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationdata',
            name='completeness',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='Completeness (%)'),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='date_percentage',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='Numeric percentage (%)'),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='numeric_percentage',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='Numeric percentage (%)'),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='uniqueness',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True, verbose_name='Uniqueness (%)'),
        ),
    ]
