# Generated by Django 3.1.3 on 2020-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20201214_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationdata',
            name='non_null_count',
            field=models.IntegerField(null=True, verbose_name='Non-null count'),
        ),
    ]
