# Generated by Django 3.1.3 on 2020-12-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20201214_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationdata',
            name='completeness',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Completeness (%)'),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='date_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Numeric percentage (%)'),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='max_value',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='min_value',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='numeric_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Numeric percentage (%)'),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='uniqueness',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Uniqueness (%)'),
        ),
    ]
