# Generated by Django 3.0.8 on 2020-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationdata',
            name='completeness',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='date_percentage',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='max_value',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='min_value',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='numeric_percentage',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='explorationdata',
            name='uniqueness',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
