# Generated by Django 3.0.8 on 2020-10-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilit', '0004_auto_20201019_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExplorationData',
        ),
    ]
