# Generated by Django 3.0.8 on 2020-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilit', '0006_auto_20201105_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulesbasedprofilefiles',
            old_name='total_failed_entries',
            new_name='total_data_points',
        ),
        migrations.AddField(
            model_name='rulesbasedprofilefiles',
            name='total_errors',
            field=models.IntegerField(null=True),
        ),
    ]
