# Generated by Django 3.0.8 on 2020-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilit', '0007_auto_20201116_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesbasedprofilefiles',
            name='total_failed_data_points',
            field=models.IntegerField(null=True),
        ),
    ]
